import streamlit as st
from dotenv import load_dotenv
from streamlit_mic_recorder import mic_recorder
import os
import time
import requests
import json

# 1. Load Environment Variables
load_dotenv()

# 2. Page Configuration
st.set_page_config(page_title="AI Researcher", page_icon="🕵️‍♂️", layout="wide")
st.title("🕵️‍♂️ Autonomous Research Chat (Voice & Discord)")

# 3. Sidebar: Settings
with st.sidebar:
    st.header("⚙️ Settings")
    
    # API Key Check
    if os.environ.get("OPENAI_API_KEY"):
        st.success("✅ API Key Loaded")
    else:
        st.error("❌ API Key Missing")
        st.info("Please set OPENAI_API_KEY in your .env file")
        
    # Discord Check
    if os.environ.get("DISCORD_WEBHOOK_URL"):
        st.success("✅ Discord Webhook Loaded")
    else:
        st.warning("⚠️ Discord Webhook Missing")

# 4. Helper Function: Discord Broadcast
def send_to_discord(report_text):
    webhook_url = os.environ.get("DISCORD_WEBHOOK_URL")
    if not webhook_url:
        return "❌ Error: Discord Webhook URL missing in .env"

    # Truncate to avoid Discord 2000 char limit errors
    short_report = report_text[:1900] + "..." if len(report_text) > 1900 else report_text

    data = {
        "content": "🕵️‍♂️ **New Research Report Incoming!**",
        "embeds": [
            {
                "title": "Autonomous Research Findings",
                "description": short_report,
                "color": 5814783, # Blue
                "footer": {
                    "text": "Generated by AI Agent via Streamlit"
                }
            }
        ]
    }
    
    try:
        response = requests.post(
            webhook_url, 
            data=json.dumps(data), 
            headers={"Content-Type": "application/json"}
        )
        if response.status_code == 204:
            return "✅ Sent to Discord Server!"
        else:
            return f"❌ Failed: {response.status_code} - {response.text}"
    except Exception as e:
        return f"❌ Connection Error: {e}"

# 5. Initialize Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# 6. Display Previous Messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# 7. Safe Imports
try:
    from app.graphs.graph import graph
    from app.voice.listener import transcribe_audio 
    from app.voice.speaker import generate_audio
    from app.utils.pdf_generator import create_pdf
except Exception as e:
    st.error(f"❌ Error importing modules: {e}")
    st.stop()

# --- INPUT AREA ---
col1, col2 = st.columns([8, 1])

with col1:
    text_input = st.chat_input("What would you like to research?")

with col2:
    audio_data = mic_recorder(
        start_prompt="🎤",
        stop_prompt="🛑",
        just_once=True,
        key='recorder'
    )

user_prompt = None
auto_speak = False 

if text_input:
    user_prompt = text_input
elif audio_data is not None and audio_data['bytes'] is not None:
    with st.spinner("👂 Listening..."):
        user_prompt = transcribe_audio(audio_data['bytes'])
        auto_speak = True 

# --- AGENT LOGIC ---
if user_prompt:
    
    st.session_state.messages.append({"role": "user", "content": user_prompt})
    with st.chat_message("user"):
        st.markdown(user_prompt)

    with st.chat_message("assistant"):
        status_placeholder = st.empty()
        response_placeholder = st.empty()
        
        def stream_text(text):
            for word in text.split(" "):
                yield word + " "
                time.sleep(0.02)
        
        config = {"configurable": {"thread_id": "1"}}
        initial_state = {"task": user_prompt, "current_step": 0, "context": []}
        final_report = ""

        try:
            status_text = "🧠 Thinking..."
            status_placeholder.markdown(f"*{status_text}*")
            
            # Run Graph
            for event in graph.stream(initial_state, config=config):
                for key, value in event.items():
                    
                    if key == "planner":
                        status_placeholder.markdown("🗺️ **Plan Created.**")
                        
                    elif key == "researcher":
                        step_num = value.get("current_step", 1)
                        status_placeholder.markdown(f"🔎 **Researching Step {step_num}...**")
                        
                    elif key == "reporter":
                        status_placeholder.markdown("📝 **Writing Report...**")
                        final_report = value.get("report", "No report generated.")

            # --- FINISHED ---
            status_placeholder.empty()
            
            # Stream Text Response
            response_placeholder.write_stream(stream_text(final_report))
            st.session_state.messages.append({"role": "assistant", "content": final_report})
            
            # --- POST-PROCESSING TOOLS ---
            if final_report:
                
                # 1. GENERATE PDF
                pdf_path = create_pdf(final_report)
                
                # Create Layout for Buttons
                st.markdown("---")
                btn_col1, btn_col2, btn_col3 = st.columns(3)
                
                # A. Download PDF
                with btn_col1:
                    with open(pdf_path, "rb") as f:
                        st.download_button(
                            label="📥 Download PDF",
                            data=f,
                            file_name="research_report.pdf",
                            mime="application/pdf"
                        )
                
                # B. Replay Voice
                with btn_col2:
                    if st.button("🔊 Replay Voice"):
                        audio_file = generate_audio(final_report)
                        st.audio(audio_file, format="audio/mp3", autoplay=True)

                # C. Discord Broadcast
                with btn_col3:
                    if st.button("🚀 Send to Discord"):
                        with st.spinner("Broadcasting..."):
                            result = send_to_discord(final_report)
                            if "✅" in result:
                                st.success(result)
                            else:
                                st.error(result)

                # 2. AUTO-PLAY VOICE (If enabled)
                if auto_speak:
                    with st.spinner("🔊 Generating Audio..."):
                        audio_file = generate_audio(final_report)
                        st.audio(audio_file, format="audio/mp3", autoplay=True)
        
        except Exception as e:
            st.error(f"An error occurred: {e}")