from typing import Annotated, List, TypedDict
import operator

class AgentState(TypedDict):
    # The original user goal
    task: str
    # The plan generated by the Planner
    plan: List[str]
    # Collected research data
    context: Annotated[List[str], operator.add]
    # The final report
    report: str
    # Current step in the plan
    current_step: int